default:
  trainer: single
  logger: wandb

  task:
    dataset: lmdb_noisy #single_point_lmdb
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy
  optim:
    optimizer: AdamW
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True
    # constant_noise: False

  mode: train
  adsorbates: all   # {"*O", "*OH", "*OH2", "*H"}
  adsorbates_ref_dir: /network/scratch/s/schmidtv/ocp/datasets/ocp/per_ads
  dataset:
    default_val: val_id
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/train/
      normalize_labels: True
      target_mean: -1.525913953781128
      target_std: 2.279365062713623
      noisy_nodes:
        type: rand #rand or rand_deter or constant
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3
    val_id:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/val_id/
    val_ood_cat:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/val_ood_cat/
    val_ood_ads:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/val_ood_ads/
    val_ood_both:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/val_ood_both/
  # DEUP
  deup_dataset:
    create: False # "before" -> created before training (for deup) "after" -> created after training (for is2re) "" - not created
    dataset_strs: ["train", "val_id", "val_ood_cat", "val_ood_ads"]
    n_samples: 7

10k:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/10k/train

100k:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/100k/train

all: {}