default:
  trainer: single
  logger: wandb
  task:
    dataset: trajectory_lmdb
    description: "Regressing to energies and forces for DFT trajectories from OCP"
    type: regression
    metric: mae
    labels:
      - potential energy
    grad_input: atomic forces
    train_on_free_atoms: True
    eval_on_free_atoms: True
    relax_dataset:
      # path to lmdb of systems to be relaxed (uses same lmdbs as is2re)
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/val_id/
    ft_dataset:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/10k/train/
    write_pos: True
    relaxation_steps: 300
    relax_opt:
      maxstep: 0.04
      memory: 50
      damping: 1.0
      alpha: 70.0
      traj_dir: "trajectories" # specify directory you wish to log the entire relaxations, suppress otherwise
  normalizer: null
  mode: train
  optim:
    optimizer: AdamW
  model:
    otf_graph: False
    max_num_neighbors: 40
    regress_forces: from_energy # can be in{ "from_energy", "direct", "direct_with_gradient_target" }
  dataset:
    default_val: val_id
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/200k/train/
      normalize_labels: True
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    val_id:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/all/val_id
    val_ood_cat:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/all/val_ood_cat
    val_ood_ads:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/all/val_ood_ads
    val_ood_both:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/all/val_ood_both

200k:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/200k/train/

2M:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/2M/train/

20M:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/20M/train/

all:
  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/s2ef/all/train/
