# Same as rand_12i_bs32 but with dropout on output block
job:
  mem: 80GB
  cpus: 4
  gres: gpu:1
  partition: long
  # time: 15:00:00

default:
  mode: train
  optim:
    batch_size: 32
    eval_batch_size: 32
    optimizer: AdamW
    auxiliary_decay: True
    auxiliary_task_weight: 15
    energy_coefficient: 1.0
    max_epochs: 50
  cp_data_to_tmpdir: True
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True
    num_interactions: 15
    position_decoder_type: mlp
    dropout_lowest_layer: output
  trainer: single
  logger: wandb
  early_stop: False
  test_ri: True

  frame_averaging: 2D
  fa_method: se3-random

  dataset:
    train:
      noisy_nodes:
        type: rand #rand or rand_deter or constant
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3

  task:
    dataset: lmdb_noisy #single_point_lmdb  
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy

# ------------------------No dropout------------------------
runs:
  - config: faenet-is2re_aux-all
    note: "Cosine-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-all
    note: "Cosine-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: LinearWarmupCosineAnnealingLR
  
  - config: faenet-is2re_aux-all
    note: "Cosine-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-all
    note: "Cosine-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: LinearWarmupCosineAnnealingLR
# ---------------------Dropout output block-----------
  - config: faenet-is2re_aux-all
    note: "Cosine-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: LinearWarmupCosineAnnealingLR
    model:
      position_decoder_model_config:
        mlp:
          dropout_lin: 0.2
      dropout_lin: 0.2

  - config: faenet-is2re_aux-all
    note: "Cosine-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: LinearWarmupCosineAnnealingLR
    model:
      position_decoder_model_config:
        mlp:
          dropout_lin: 0.2
      dropout_lin: 0.2
  
  - config: faenet-is2re_aux-all
    note: "Cosine-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: LinearWarmupCosineAnnealingLR
    model:
      position_decoder_model_config:
        mlp:
          dropout_lin: 0.2
      dropout_lin: 0.2

  - config: faenet-is2re_aux-all
    note: "Cosine-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: LinearWarmupCosineAnnealingLR
    model:
      position_decoder_model_config:
        mlp:
          dropout_lin: 0.2
      dropout_lin: 0.2