job:
  mem: 80GB
  cpus: 4
  gres: gpu:1
  partition: long
  # time: 15:00:00

default:
  mode: train
  optim:
    batch_size: 256
    eval_batch_size: 256
    optimizer: AdamW
    auxiliary_decay: False
    auxiliary_task_weight: 1
    energy_coefficient: 0.0
    max_epochs: 50
  cp_data_to_tmpdir: True
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True

  trainer: single
  logger: wandb

  dataset:
    train:
      src: /network/scratch/s/schmidtv/ocp/datasets/ocp/is2re/all/train/
      normalize_labels: True
      target_mean: -1.525913953781128
      target_std: 2.279365062713623
      noisy_nodes:
        type: constant #rand or rand_deter or constant
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3

  task:
    dataset: lmdb_noisy #single_point_lmdb  
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy

# ----------------------all dataset-------------------
# CosineAnnealing
runs:
  - config: faenet-is2re_aux-all
    note: "Cosine-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-all
    note: "Cosine-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: LinearWarmupCosineAnnealingLR
  
  - config: faenet-is2re_aux-all
    note: "Cosine-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-all
    note: "Cosine-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: LinearWarmupCosineAnnealingLR

# Null LR
  - config: faenet-is2re_aux-all
    note: "null-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: Null

  - config: faenet-is2re_aux-all
    note: "null-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: Null
  
  - config: faenet-is2re_aux-all
    note: "null-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: Null

  - config: faenet-is2re_aux-all
    note: "null-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: Null
# ----------------------------10k-----------------------
# CosineAnnealing
  - config: faenet-is2re_aux-10k
    note: "Cosine-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-10k
    note: "Cosine-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: LinearWarmupCosineAnnealingLR
  
  - config: faenet-is2re_aux-10k
    note: "Cosine-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: LinearWarmupCosineAnnealingLR

  - config: faenet-is2re_aux-10k
    note: "Cosine-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: LinearWarmupCosineAnnealingLR

# Null LR
  - config: faenet-is2re_aux-10k
    note: "null-very-low-lr"
    optim:
      lr_initial: 0.0001
      scheduler: Null

  - config: faenet-is2re_aux-10k
    note: "null-low-lr"
    optim:
      lr_initial: 0.0005
      scheduler: Null
  
  - config: faenet-is2re_aux-10k
    note: "null-med-lr"
    optim:
      lr_initial: 0.001
      scheduler: Null

  - config: faenet-is2re_aux-10k
    note: "null-usual-lr"
    optim:
      lr_initial: 0.002
      scheduler: Null
