job:
  mem: 80GB
  cpus: 4
  gres: gpu:1
  partition: long
  # time: 15:00:00

default:
  mode: train
  optim:
    batch_size: 64
    eval_batch_size: 64
    optimizer: AdamW
    lr_initial: 0.002
    scheduler: LinearWarmupCosineAnnealingLR
    warmup_steps: 96000
    energy_coefficient: 1.0
    max_epochs: 50
    loss_position: "mae"
    loss_energy: "mae"
    auxiliary_decay: True
    energy_decay: False
  cp_data_to_tmpdir: True
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True
    num_interactions: 16
  trainer: single
  logger: wandb
  early_stop: False
  test_ri: True
  frame_averaging: 2D
  fa_method: se3-random

  dataset:
    train:
      noisy_nodes:
        type: rand
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3

  task:
    dataset: lmdb_noisy
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy

runs:
  - config: faenet-is2re_aux-all
    note: "usual linear decay to 1"
    optim:
      auxiliary_task_weight: 15
      auxiliary_min_weight: 1
      auxiliary_scheduler_type: linear

  - config: faenet-is2re_aux-all
    note: "usual linear decay to 0"
    optim:
      auxiliary_task_weight: 15
      auxiliary_min_weight: 0.0
      auxiliary_scheduler_type: linear

  - config: faenet-is2re_aux-all
    note: "Bigger linear decay to 1"
    optim:
      auxiliary_task_weight: 30
      auxiliary_min_weight: 1
      auxiliary_scheduler_type: linear

  - config: faenet-is2re_aux-all
    note: "aux CosineAnnealingLinearWarmup"
    optim:
      auxiliary_task_weight: 15
      auxiliary_warmup_steps: 6000
      auxiliary_eta_min: 0.00001
      auxiliary_scheduler_type: cosine

  - config: faenet-is2re_aux-all
    note: "aux CosineAnnealingLinearWarmup bigger init"
    optim:
      auxiliary_task_weight: 30
      auxiliary_warmup_steps: 6000
      auxiliary_eta_min: 0.00001
      auxiliary_scheduler_type: cosine

  - config: faenet-is2re_aux-all
    note: "aux CosineAnnealingLinearWarmup more warmup"
    optim:
      auxiliary_task_weight: 15
      auxiliary_warmup_steps: 12000
      auxiliary_eta_min: 0.00001
      auxiliary_scheduler_type: cosine

  - config: faenet-is2re_aux-all
    note: "aux CosineAnnealingLinearWarmup bigger eta_min"
    optim:
      auxiliary_task_weight: 15
      auxiliary_warmup_steps: 6000
      auxiliary_eta_min: 0.01
      auxiliary_scheduler_type: cosine

  - config: faenet-is2re_aux-all
    note: "aux CosineAnnealingLinearWarmup huge eta_min"
    optim:
      auxiliary_task_weight: 15
      auxiliary_warmup_steps: 6000
      auxiliary_eta_min: 1
      auxiliary_scheduler_type: cosine