# Goal: test if with sufficient inter layers we still need equivariance method
job:
  mem: 80GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  # time: 15:00:00

default:
  mode: train
  optim:
    batch_size: 128
    eval_batch_size: 128
    optimizer: AdamW
    lr_initial: 0.002
    scheduler: LinearWarmupCosineAnnealingLR
    warmup_steps: 96000
    auxiliary_decay: True
    auxiliary_task_weight: 15
    auxiliary_min_weight: 1.0
    energy_coefficient: 1.0
    max_epochs: 50
    loss_energy: "mae"
    loss_position: "mae"
  cp_data_to_tmpdir: True
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True
  trainer: single
  logger: wandb
  early_stop: False
  test_ri: True

  frame_averaging: ""
  fa_method: ""

  dataset:
    train:
      noisy_nodes:
        type: rand #rand or rand_deter or constant
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3

  task:
    dataset: lmdb_noisy #single_point_lmdb  
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy

runs:
  - config: faenet-is2re_aux-all
    note: "8 interactions"
    model:
      num_interactions: 8

  - config: faenet-is2re_aux-all
    note: "10 interactions"
    model:
      num_interactions: 10

  - config: faenet-is2re_aux-all
    note: "14 interactions"
    model:
      num_interactions: 14

  - config: faenet-is2re_aux-all
    note: "18 interactions"
    model:
      num_interactions: 18

  - config: faenet-is2re_aux-all
    note: "22 interactions"
    model:
      num_interactions: 22
  
  - config: faenet-is2re_aux-all
    note: "26 interactions"
    model:
      num_interactions: 26