job:
  mem: 80GB
  cpus: 4
  gres: gpu:1
  partition: long
  # time: 15:00:00

default:
  mode: train
  optim:
    batch_size: 128
    eval_batch_size: 128
    optimizer: AdamW
    auxiliary_decay: True
    auxiliary_task_weight: 15
    auxiliary_min_weight: 1.0
    energy_coefficient: 1.0
    max_epochs: 50
    loss_energy: "mae"
    loss_position: "mae"
  cp_data_to_tmpdir: True
  normalizer: null
  model:
    otf_graph: False
    max_num_neighbors: 40
    noisy_nodes: True
    num_interactions: 10
  trainer: single
  logger: wandb
  early_stop: False
  test_ri: True

  dataset:
    train:
      noisy_nodes:
        type: rand #rand or rand_deter or constant
        interpolate_threshold: 0.5
        min_interpolate_factor: 0.0
        gaussian_noise_std: 0.3

  task:
    dataset: lmdb_noisy #single_point_lmdb  
    description: "Relaxed state energy prediction from initial structure."
    type: regression
    metric: mae
    labels:
      - relaxed energy

runs:
  - config: faenet-is2re_aux-all
    note: "se3-random"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: se3-random
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: random
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: det
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: all
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: se3-all
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: se3-random
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: se3-det
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: multiple
  - config: faenet-is2re_aux-all
    note: "1 aux weight"
    optim:
      lr_initial: 0.002
    frame_averaging: 2D
    fa_method: se3-multiple