job:
    mem: 32GB
    cpus: 4
    gres: gpu:rtx8000:1
    partition: long

default:
    test_ri: True
    mode: train
    wandb_name: alvaro-carbonero-math # DO NOT USE THIS CONFIG FILE. IT'S BAD!
    wandb_project: ocp-alvaro

runs:
    # Run 1
    - config: faenet-is2re-10k
      note: 'default-with-train-mode'
