job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 15:00:00

default:
  wandb_name: alvaro-carbonero-math
  wandb_project: ocp-alvaro
  wandb_tags: "best-config"
  test_ri: True
  mode: train
  graph_rewiring: remove-tag-0
  note: "top-run"
  frame_averaging: 2D
  fa_method: se3-random
  cp_data_to_tmpdir: True
  model:
    edge_embed_type: all_rij
    mp_type: updownscale_base
    phys_embeds: True
    tag_hidden_channels: 32
    pg_hidden_channels: 96
    energy_head: weighted-av-final-embeds
    complex_mp: True
    graph_norm: True
    hidden_channels: 352
    num_filters: 288
    num_gaussians: 68
    num_interactions: 5
    second_layer_MLP: False
    skip_co: concat
    cutoff: 4.0
  optim:
    batch_size: 256
    eval_batch_size: 256
    lr_initial: 0.002
    scheduler: LinearWarmupCosineAnnealingLR
    max_epochs: 9
    eval_every: 0.4

runs:
  # - config: faenet-is2re-10k

  # - config: faenet-is2re-10k
    # is_disconnected: True
 
  - config: indfaenet-is2re-all
    note: so that cat get old dimensions
    model:
      hidden_channels: 352
      num_gaussians: 99
      num_filters: 448

  - config: indfaenet-is2re-all
    note: dimensions of both smaller
    model:
      hidden_channels: 176
      num_gaussians: 50
      num_filters: 224

  - config: indfaenet-is2re-all
    note: so that ads get old dimensions
    model:
      hidden_channels: 704 
      num_gaussians: 200
      num_filters: 896

  - config: indfaenet-is2re-all
    note: so that their average is old dimension
    model:
      hidden_channels: 468 
      num_gaussians: 132
      num_filters: 596
 
  # - config: indfaenet-is2re-10k
 
  # - config: afaenet-is2re-all
    # model:
      # afaenet_gat_mode: v1
