job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 18:00:00

default:
  wandb_name: alvaro-carbonero-math
  wandb_project: ocp-alvaro
  graph_rewiring: remove-tag-0
  model:
   tag_hidden_channels: 32
   pg_hidden_channels: 32
   phys_embeds: True
   otf_graph: False
   max_num_neighbors: 40
   hidden_channels: 142
   graph_rewiring: remove-0-tag
  optim:
    batch_size: 32
    eval_batch_size: 32
    max_epochs: 30

runs:
  - config: gemnet_t-is2re-all

  - config: gemnet_t-is2re-all
    is_disconnected: True

  #- config: depgemnet_t-is2re-all

  #- config: indgemnet_t-is2re-all

  #- config: agemnet_t-is2re-all
