job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long
  time: 15:00:00

default:
  # wandb_name: alvaro-carbonero-math
  wandb_project: ocp-alvaro
  wandb_tags: "gflownet-model"
  test_ri: True
  mode: train
  graph_rewiring: remove-tag-0
  # graph_rewiring: ""
  frame_averaging: 2D
  fa_method: se3-random
  cp_data_to_tmpdir: True
  is_disconnected: true
  model:
    edge_embed_type: all_rij
    mp_type: updownscale_base
    phys_embeds: True
    tag_hidden_channels: 32
    pg_hidden_channels: 96
    energy_head: weighted-av-final-embeds
    complex_mp: True
    graph_norm: True
    hidden_channels: 352
    num_filters: 288
    num_gaussians: 68
    num_interactions: 5
    second_layer_MLP: False
    skip_co: concat
    cutoff: 4.0
  optim:
    batch_size: 256
    eval_batch_size: 256
    lr_initial: 0.002
    scheduler: LinearWarmupCosineAnnealingLR
    max_epochs: 9
    eval_every: 0.4

runs:

  - config: faenet-is2re-all
    note: baseline faenet

  - config: depfaenet-is2re-all
    note: depfaenet baseline

  - config: depfaenet-is2re-all
    note: depfaenet per-adsorbate
    adsorbates: '*O, *OH, *OH2, *H'

  - config: depfaenet-is2re-all
    note: To be used for continue from dir

  # - config: depfaenet-is2re-all
  #   note: Fine-tune on per-ads-dataset
  #   continue_from_dir: /network/scratch/a/alexandre.duval/ocp/runs/2935198
  #   adsorbates: {'*O', '*OH', '*OH2', '*H'}
  #   optim:
  #     max_epochs: 3
