job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long

default:
  config: disconnected-is2re-all
  test_ri: True
  mode: train
  wandb_tags: 'baseline'
  wandb_name: alvaro-carbonero-math
  wandb_project: ocp-alvaro
  cp_data_to_tmpdir: True
  fa_frames: se3-random
  frame_averaging: 2D
  graph_rewiring: remove-tag-0
  model:
    pg_hidden_channels: 64
    phys_embeds: True
    phys_hidden_channels: 0
    tag_hidden_channels: 64
    energy_head: weighted-av-final-embeds
  optim:
    max_epochs: 12  

runs:
  # Run 1
  - {}

  # Run 2
  - config: faenet-is2re-all

  # Run 3
#  - optim:
#      lr_initial: 0.0001

  # Run 4
#  - model:
#      pg_hidden_channels: 32
#    optim:
#      lr_initial: 0.0001
